# Site settings
title: Keep This Moment
email: mbajur@gmail.com
description: "hardcore punk photos and videos"
baseurl: ""
url: "http://keepthismoment.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
