# Site settings
title: Keep This Moment
email: mbajur@gmail.com
description: "stage dives & high fives"
baseurl: "https://keepthismoment.com/"
url: "https://keepthismoment.com"
deploy_dir: 'deploy@keepthismoment.com:/home/deploy/ktm'

# Build settings
markdown: kramdown
permalink: /:categories/:title/
exclude: [vendor]