# Site settings
title: Keep This Moment
email: mbajur@gmail.com
description: "stage dives & high fives"
baseurl: ""
url: "http://localhost:4000"

# Build settings
markdown: kramdown
permalink: /:categories/:title/

gems:
- jekyll-autoprefixer