# Site settings
title: Keep This Moment
email: mbajur@gmail.com
description: "hardcore punk photos and videos"
baseurl: "http://keepthismoment.com/"
url: "http://keepthismoment.com"
deploy_dir: 'deploy@keepthismoment.com:/home/deploy/ktm'

# Misc
likeit_url: http://likeit.platform.hcxp.co


# Build settings
markdown: kramdown
permalink: /:categories/:title
exclude: [vendor]